version: 2.1
# Use a package of configuration called an orb.
# orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
  # Name the workflow "welcome"
  # welcome:
    # Run the welcome/run job in its own container
    # jobs:
      # - welcome/run

jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            # - run:
                  # name: Install Dependencies
                  # command: npm install
            # - save_cache:
                  # key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  # paths:
                      # - ./node_modules
            # - run:
                  # name: Build
                  # command: npm build
            - run:
                  name: Firebase Deploy
                  command: ./node_modules/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
